server:
  port: 80

spring:
  datasource:
    username: admin
    password: adminadmin
    url: jdbc:mariadb://crawling-server.c4y9vm1irfhh.ap-northeast-2.rds.amazonaws.com/classmoa
    driver-class-name: org.mariadb.jdbc.Driver

  #의존성 추가
  servlet:
    multipart:
      max-request-size: 30MB
      max-file-size: 30MB

  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    hibernate.ddl-auto: update
    properties:
      hibernate.format_sql: true
#  sql.init.mode: always


#의존성 추가
cloud:
  aws:
    credentials:
      accessKey: AKIARIZNV6JYGNGN2CZH # IAM 사용자 엑세스 키
      secretKey: 67CUpdBvEYNRhF4C3zW1pZ7C8GfUuy0DdRE0zn7L # IAM 사용자 비밀 엑세스 키
    s3:
      bucketName: classmoaimage # 버킷명
    region:
      static: ap-northeast-2 # 리전
    stack:
      auto: false # Spring Cloud는 환경 또는 스택을 기반으로 이를 자동으로 감지
